import Head from "next/head";
// import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import CoinData from "../components/CoinData";
import Swap from "../components/Swap";
import ManualHeader from "../components/ManualHeader";

export default function Home() {
  const [swapLoss, setSwapLoss] = useState();
  const getSwapLoss = (inputSwapLoss) => {
    setSwapLoss(inputSwapLoss);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Transify</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ManualHeader onAddSwapLoss={getSwapLoss} />
      <div className={styles.coinAndSwap}>
        <CoinData />
        <Swap swapLoss={swapLoss} />
      </div>
    </div>
  );
}
