import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import CoinData from "../components/coinData";
import Swap from "../components/Swap";
import ManualHeader from "../components/ManualHeader";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Transify</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ManualHeader />
      <div className={styles.coinAndSwap}>
        <CoinData />
        <Swap />
      </div>
    </div>
  );
}
