import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";
import CoinData from "../components/CoinData";
import Swap from "../components/Swap";
import ManualHeader from "../components/ManualHeader";
import { useState } from "react";
import Footer from "../components/Footer";


export default function Home() {
  const [apiData, setApiData] = useState();
  const getData = (apiData) => {
    setApiData(apiData);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Transify</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <ManualHeader />
      <div className={styles.coinAndSwap}>
        <CoinData onAddApiData={getData} />
        <Swap data={apiData} />
      </div>
      <Footer />
    </div>
  );
}